### ISSUE TITLE
Plugin configuration doesn't work

### ISSUE THREAD

**Issue by Filuman** [GaelicThunder/Experience-Plugin-Pwnagotchi#14]
Hi there,

I'm currently having an issue with the plugin. I installed the plugin correctly, I think, but it doesn't show up on the screen. The plugin is activated through webconfig. 
When I set the position for the plugin in config.toml, the whole Pwnagotchi doesn't work. The screen stays blank and the web-ui doesn't load, so I left the position-cofiguration empty.
The age plugin does work, but the exp plugin does not, as I stated.

I sadly can't find any solution.

I would be grateful if somebody could help me.
Kind regards,
Filu

**Comment by GaelicThunder** [comment]
Hello there!

I must admit, im not using the Pwnagotchi since 2 years now, but i can try and re-test it in a couple of days, if you are willing to wait a little.
In the meantime, can you try activating it only from the config (In your config.toml file, add:   main.plugins.exp.enabled = true) and share a [log](https://pwnagotchi.ai/usage/#pwnlog)?
Also, could you share more of your configuration? What kind of screen are you trying? What positions did you set (when you set them)? 
Thanks!

**Comment by Filuman** [comment]
Hi,

thank you for your help! Yes, I can wait, that's not a problem. I activated it only from the config, but it didn't change anything, sadly.
Here are the logs: [Pastebin](https://pastebin.com/Q6jPxZAP). I removed some information, just so you know. Also I observed that the pwngrid-api wasn't starting, it just wouldn't continue (As you can see in the end of the log). I dont know if that could have something to do with my problem.

I'm using an Raspberry Pi zero w paired with a waveshare 2.13 inch display with Jayofelony's bookworm image. I set the standard position from the example shown in the readme.

Kind regards,
Filu

**Comment by GaelicThunder** [comment]
I noted that you are not using the standard image but the Jayofelony's bookworm one. While im not experienced with that image, i'll try and recreate the error myself. Could you point out the release you used pretty please?

**Comment by Filuman** [comment]
Yes, of course! Here it is: [github.com/jayofelony/pwnagotchi-bookworm/releases/tag/v2.8.4](https://github.com/jayofelony/pwnagotchi-bookworm/releases/tag/v2.8.4). I used this image because it supports the waveshare v4 display.
Could it be that it isn't working just because of the image? 

Kind regards,
Filu

**Comment by GaelicThunder** [comment]
The thing is, that image is for 64bit Pi's ( Pi Zero W **2** ) as stated in the readme:

> This fork of [Pwnagotchi](https://www.pwnagotchi.ai/) is only for 64-bit Raspberry Pi's. Such as the 02W, 3(b+) and 4(b) and the new Raspberry Pi 5!!.
> 
> The RPi5 can only be used headless currently. (without display.)
> 
> If you are using an older 32-bit version Raspberry Pi, ZeroWH, use this [fork](https://github.com/jayofelony/pwnagotchi-torch/releases/tag/v2.6.4) and make sure you download the armhf version.

so, maybe something it's not working because of it?

**Comment by Filuman** [comment]
Oh, I'm sorry! I meant that version of course. I used that one originally, but I updated to the newer version in the process of setting up the pwnagotchi. I don't know how this is supposed to work with 32 bit, but ¯\_(ツ)_/¯

So, um, what do I do now?

Kind regards,
Filu

**Comment by GaelicThunder** [comment]
Best thing to do would try to re-flash everything from zero with this [pwnagotchi-torch](https://github.com/jayofelony/pwnagotchi-torch/releases/tag/v2.8.4) and not the other one you linked which is [pwnagotchi-bookworm](https://github.com/jayofelony/pwnagotchi-bookworm/releases/tag/v2.8.4).
it made me laugh that even jayofelony said:

> A new version, since still soooooooo many people use this image for their zeroW. I do suggest, if you can, to transition to a 64-bit RPi as 32-bit is reaching EOL.
> 
> Have fun.

so it must be something that happened quite a lot ahahahah

I can try using the same image as yours and let you know how it went tho, you tell me c:

**Comment by Filuman** [comment]
So, I installed the torch version now...
When I  try to go to the directory, where the plugins should be stored (/usr/local/src/pwnagotchi/plugins/default) it doesn't exist, it only goes until src with these two files: 
![image](https://github.com/GaelicThunder/Experience-Plugin-Pwnagotchi/assets/76902122/fdc65465-d206-4470-be9b-804ac2b89b06)
On the other version of the image, the directory was present, but now, it isn't. That's why I can't add the plugins now. :(
Do you have any idea why this could happend?

Kind regards,
Filu

**Comment by GaelicThunder** [comment]
I have no idea to be honest, it's probably better asking in that repo

**Comment by rai68** [comment]
alot has changed please use https://github.com/jayofelony/pwnagotchi , releases contain images for both 32bit (zero v1) and 64bit(zero v2 and up)

**Comment by GaelicThunder** [comment]
@rai68 thanks for the headsup! Guess we will wait for a feedback from @Filuman  to see if everything works as intended. If it doesnt, then we can start debugging it for real c:

**Comment by Filuman** [comment]
Ok, will definitely be trying that! Thank you for the info.

**Comment by Filuman** [comment]
Hi there,

After reflashing the firmware, I was finally able to configure the plugin correctly. This time I placed the plugin in the default custom plugins directory and it actually showed up.
Now everything works fine! :D

Thanks for your help @GaelicThunder and @rai68! ^_^

Kind Regards,
Filu
