### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by idontneedonetho** [GaelicThunder/Experience-Plugin-Pwnagotchi#4]
"error while loading /usr/local/share/pwnagotchi/installed-plugins/exp.py: Expecting value: line 1 column 1 (char 0)" pops up when I try to load the plugin, I reinstalled exp.py and nothing changed. Nothing displays on my screen either.

**Comment by mbudget0x01** [comment]
According to this it sounds like a json error. probably an empty json file, when something whent wrong. Is there a file present under `/usr/local/share/pwnagotchi/installed-plugins/exp_stats.json` ? If so, please check if its empty. If it is empty you can try to delte it.
Please let us now if this solved your problem, so we can fix the plugin :-)

**Comment by idontneedonetho** [comment]
Removing the .json file fixed it, but also wiped my custom x, y locations. Easy enough to fix that though! Thank you!

**Comment by mbudget0x01** [comment]
Thanks for your answer. I will reopen this issue as there is just a workaround but no proper bugfix to this.
Can you explain me what you mean by custom x,y coordinates, as this sounds like something that is affected but not part of this plugin?
Thanks in Advance.

**Comment by idontneedonetho** [comment]
> Thanks for your answer. I will reopen this issue as there is just a workaround but no proper bugfix to this.
> Can you explain me what you mean by custom x,y coordinates, as this sounds like something that is affected but not part of this plugin?
> Thanks in Advance.

By custom x, y I mean I modified:
`def on_ui_setup(self, ui):
        ui.add_element('Lv', LabeledValue(color=BLACK, label='Lv', value=0, position=(ui.width() / 2 - 125, 95),
                                           label_font=fonts.Bold, text_font=fonts.Medium))
        ui.add_element('Exp', LabeledValue(color=BLACK, label='Exp', value=0, position=(ui.width() / 2 - 85, 95),
                                           label_font=fonts.Bold, text_font=fonts.Medium))`
changing "125" to "121" and "85" to "82" so that it sits right under the face but above the password display plugin.

**Comment by mbudget0x01** [comment]
Thanks for your explainations :-).
I opend an issue to implement this via config #6. As we are quiet busy at the time. Please don't expect it not to be implemented immedeatly...
