### ISSUE TITLE
Custom X,Y Coordinates for the progress bar

### ISSUE THREAD

**Issue by mbudget0x01** [GaelicThunder/Experience-Plugin-Pwnagotchi#6]
There seems like there is the wish to adjust the coordinates of the progress bar manually. A solution would be to make this configurable using the config file.

from issue number #4:
> > Thanks for your answer. I will reopen this issue as there is just a workaround but no proper bugfix to this.
> > Can you explain me what you mean by custom x,y coordinates, as this sounds like something that is affected but not part of this plugin?
> > Thanks in Advance.
> 
> By custom x, y I mean I modified:
> `def on_ui_setup(self, ui): ui.add_element('Lv', LabeledValue(color=BLACK, label='Lv', value=0, position=(ui.width() / 2 - 125, 95), label_font=fonts.Bold, text_font=fonts.Medium)) ui.add_element('Exp', LabeledValue(color=BLACK, label='Exp', value=0, position=(ui.width() / 2 - 85, 95), label_font=fonts.Bold, text_font=fonts.Medium))`
> changing "125" to "121" and "85" to "82" so that it sits right under the face but above the password display plugin.

**Comment by GaelicThunder** [comment]
Added on last commit [https://github.com/GaelicThunder/Experience-Plugin-Pwnagotchi/commit/fdc0bd7a6ede93524bbcbac2f7951038e3f9f8e3](url) by @hannadiamond
